<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cl.duoc.hotel</groupId>
    <artifactId>hotel-perros-parent</artifactId>
    <version>2.0</version>
    <packaging>pom</packaging>

    <name>hotel-perros-parent</name>
    <description>Proyecto Padre para el Hotel de Mascotas</description>

    <modules>
        <module>api-gateway</module>
        <module>microservices/ms-duenos</module>
        <module>microservices/ms-empleados</module>
        <module>microservices/ms-facturacion</module>
        <module>microservices/ms-habitaciones</module>
        <module>microservices/ms-inventario</module>
        <module>microservices/ms-mascotas</module>
        <module>microservices/ms-notificaciones</module>
        <module>microservices/ms-reportes</module>
        <module>microservices/ms-reservas</module>
        <module>microservices/ms-servicios</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
</project>