spring:
  application:
    name: ms-servicios
  datasource:
    url: jdbc:h2:mem:ms-servicios;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
server:
  port: 8087
springdoc:
  swagger-ui:
    path: /swagger-ui.html