# Configuración del Servidor
spring.application.name=microservicio-reservas
server.port=8080

# Configuración de la Base de Datos (Datasource)
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_perros_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
# Dialecto para MySQL 8
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# "update" crea las tablas automáticamente si no existen basándose en tus entidades
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola para facilitar el debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de Migraciones Iniciales (SQL Script)
# Le dice a Spring que siempre ejecute el archivo data.sql al iniciar
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

